version: '3.4'

services:
  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: OrderApi/Dockerfile


  customerapi:
    image: ${DOCKER_REGISTRY-}customersapi
    build:
      context: .
      dockerfile: CustomersAPI/Dockerfile



  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
 

